#this file will configure pytest to automatically find test_*.py files in the tests directory and run them when pytest is called from the command line.
#no matter who runs it or on which machine

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v

